#!/usr/bin/env bash
#This script prints Best school and at Hi at the 9 iteration
count=1
while [ $count -le 10 ]; do
      if [ $count -eq 9 ]; then
      	 echo -e "Best School\nHi"
      else
	echo "Best School"
      fi
      count=$((count + 1))
done
	 	 
